# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16c0898d3304b6a9548a66df8fb91bf612d508116872768e75014bfec4d6dc01d1a6bddde3953b60be673d2797a702940c49a75340f2370d583f4f4a245e339e

test:
  secret_key_base: 79cb39b728042aee4c9e856ffb6136dd8f4ab59654984e3d61d327d83913649d7b7975d9d02645d135265c77d9bf1147c9920418bca4dab7ed65bc40c2dbcdd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
