# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9686da7e7812d6b6ce7b46d85f1d0168b17bdf1c2298f71d5a3caaddb5e30fd0b4465eee48478647e0edb667a4877c5b972e4e7823307026a0f0b739a97bd0c

test:
  secret_key_base: 1fc37764bf85ac08635a6b122c605f63879480e9e4f269569b1fbcd5f7f6d864003eff6aad37e7b286440ca472285ceef874fd53c0a0f069e8a5cdf206594ae6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
